version: '3.8'

services:
  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: order-service
      POSTGRES_PASSWORD: order-service
      POSTGRES_DB: order-service
    ports:
      - "6442:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - commerce-network

  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      POSTGRES_USER: product-service
      POSTGRES_PASSWORD: product-service
      POSTGRES_DB: product-service
    ports:
      - "6443:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - commerce-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - commerce-network

volumes:
  order-db-data:
  product-db-data:
  rabbitmq-data:

networks:
  commerce-network:
    driver: bridge 